PagerDuty-Demo
fusebit/everyauth-express pull request #27
Opened 2022-05-03 01:33 UTC by matthewzhaocc

2022-05-06 15:52 UTC, degrammer commented on examples/pagerduty/index.js
> +  const me = await (await sdk.get('/users/me')).data.user;
Seems there is an extra await here?

2022-05-06 15:53 UTC, degrammer commented on examples/pagerduty/index.js
> +  const me = await (await sdk.get('/users/me')).data.user;
Also, I'm wondering if a new incident can be created from the API? would be an interesting part of this demo!

2022-05-06 15:54 UTC, degrammer commented on examples/pagerduty/package.json
> +    "@fusebit/everyauth-express": "^1.0.3",
Change to "@fusebit/everyauth-express": "*"

2022-05-06 15:55 UTC, degrammer requested changes
Review comments, also delete package.lock file, we don't include them in examples.

2022-05-06 15:57 UTC, degrammer commented on examples/pagerduty/README.md
> +  const me = await (await sdk.get('/users/me')).data.user;
Organize this code in blocks/sections, so is easier to follow what each line is doing, e.g:
1. Get the stored credentials for the pagerduty service
2. Fetch the authorizing user profile, etc

See an example https://github.com/degrammer/everyauth-express/blob/everyauth-stackoverflow/examples/stackoverflow/index.js#L67

2022-05-17 12:58 UTC, matthewzhaocc reviewed
This is the coolest ever!

2022-05-17 14:30 UTC, degrammer commented on examples/pagerduty/README.md
> +```bash\
remove extra \

2022-05-17 14:32 UTC, degrammer requested changes
Small comment and also, can we remove any package-lock from the examples, I'm seeing some of them are being added

2022-05-17 19:04 UTC, matthewzhaocc commented on examples/pagerduty/README.md
> +```bash\
Done

2022-05-17 20:41 UTC, degrammer approved these changes
LGTM

2022-05-17 20:42 UTC, merged